#!/bin/bash
echo "Stopping all containers..."
docker stop $(docker ps -a -q)
echo "Removing all containers..."
docker rm $(docker ps -a -q)
echo "Removing all images..."
docker rmi $(docker images -q)
echo "Removing all volumes..."
docker volume prune --all
echo "Removing all networks..."
docker network prune
echo "Removing builder cache..."
docker builder prune -f
echo "Docker cleanup complete!"

