kind: Service
apiVersion: v1
metadata:
  name: webapp-hello-service-v1
spec:
  type: NodePort
  selector:
    app: webapp-hello-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
