apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: nginx-ingress
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"nginx-ingress","app.kubernetes.io/name":"nginx-ingress"},"name":"nginx-ingress","namespace":"nginx-ingress"}}
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: nginx-ingress
      app.kubernetes.io/name: nginx-ingress
    name: nginx-ingress
    namespace: nginx-ingress
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"admission-webhook","app.kubernetes.io/instance":"nginx-ingress","app.kubernetes.io/name":"nginx-ingress"},"name":"nginx-ingress-admission","namespace":"nginx-ingress"}}
    labels:
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: nginx-ingress
      app.kubernetes.io/name: nginx-ingress
    name: nginx-ingress-admission
    namespace: nginx-ingress
kind: List
metadata:
  resourceVersion: ""